name: PyInstaller

on: [push]

jobs:
  build:

    runs-on: windows-latest
    env:
       working-directory: ./standalone
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: build with pyinstaller
      run: |
        pyinstaller TissUUmaps.spec
    - name: copy vips bin files
      run: |
        cp vips-dev-8.10/bin/* dist/TissUUmaps/
    - name: rename Qt to Qt5
      run: |
        mv dist/TissUUmaps/PyQt5/Qt dist/TissUUmaps/PyQt5/Qt5
